"""Add metadata fields to Recibo model

Revision ID: 007e731f6a40
Revises: 8dcd4c965036
Create Date: 2025-07-14 10:11:03.900654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007e731f6a40'
down_revision = '8dcd4c965036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lugar_entrega', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cargo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('liquido_a_pagar', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tipo_liquidacion', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.drop_column('tipo_liquidacion')
        batch_op.drop_column('liquido_a_pagar')
        batch_op.drop_column('cargo')
        batch_op.drop_column('lugar_entrega')
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
