"""Add filepath to Recibo model

Revision ID: 18d3366d46ec
Revises: fdcdfd9fa355
Create Date: 2025-07-25 15:08:29.107401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18d3366d46ec'
down_revision = 'fdcdfd9fa355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=500), nullable=False))
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['filepath'])

    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('observacion',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_registro_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('area',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('area',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('registro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_timestamp'))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('observacion',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
