"""Actualizacion de modelos de usuario y recibos

Revision ID: 45c4a6a1cea6
Revises: 5ed2ecd44deb
Create Date: 2025-07-21 13:33:38.118577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45c4a6a1cea6'
down_revision = '5ed2ecd44deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('upload_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('cargo')
        batch_op.drop_column('liquido_a_pagar')
        batch_op.drop_column('lugar_entrega')
        batch_op.drop_column('categoria')
        batch_op.drop_column('tipo_liquidacion')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('registered_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('is_moderator',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('is_owner',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_owner',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('is_moderator',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('registered_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('recibo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_liquidacion', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('categoria', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('lugar_entrega', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('liquido_a_pagar', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('cargo', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('upload_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
