"""Rellenar datos de registered_at y last_login para usuarios existentes

Revision ID: 583ae37744ef
Revises: c1774d880264
Create Date: 2025-07-22 11:29:34.391690

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
import pytz

# Definir la zona horaria de Argentina (Buenos Aires) - No se usa directamente aquí, pero es buena práctica mantenerla
ARGENTINA_TIMEZONE = pytz.timezone('America/Argentina/Buenos_Aires')

# revision identifiers, used by Alembic.
# Estos IDs son generados automáticamente por Alembic y son correctos.
revision = '583ae37744ef'
down_revision = 'c1774d880264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rellenar el campo 'registered_at' para usuarios existentes que lo tienen NULL
    # Establecer la fecha de registro a la fecha y hora actual en UTC
    op.execute(
        sa.text(
            "UPDATE user SET registered_at = :now WHERE registered_at IS NULL"
        ).bindparams(now=datetime.utcnow())
    )

    # Rellenar el campo 'last_login' para usuarios existentes que lo tienen NULL
    # Establecer la última conexión a la fecha y hora actual en UTC
    op.execute(
        sa.text(
            "UPDATE user SET last_login = :now WHERE last_login IS NULL"
        ).bindparams(now=datetime.utcnow())
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # En el downgrade, no revertimos los datos rellenados, ya que eso podría ser destructivo.
    # Si realmente necesitaras revertir, tendrías que pensar en cómo manejar los datos.
    pass
    # ### end Alembic commands ###
