"""Actualizacion de modelos de usuario y recibos

Revision ID: c1774d880264
Revises: 45c4a6a1cea6
Create Date: 2025-07-21 13:44:12.391337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1774d880264'
down_revision = '45c4a6a1cea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('area')

    # ### end Alembic commands ###
