"""Actualizar registered_at de cero a fecha actual

Revision ID: fdcdfd9fa355
Revises: 583ae37744ef
Create Date: 2025-07-22 11:49:12.644928

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime
import pytz

# Definir la zona horaria de Argentina (Buenos Aires)
ARGENTINA_TIMEZONE = pytz.timezone('America/Argentina/Buenos_Aires')

# revision identifiers, used by Alembic.
revision = 'fdcdfd9fa355'
down_revision = '583ae37744ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Actualizar 'registered_at' para usuarios donde es '0000-00-00 00:00:00'
    op.execute(
        sa.text(
            "UPDATE user SET registered_at = :now WHERE registered_at = '0000-00-00 00:00:00'"
        ).bindparams(now=datetime.utcnow())
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # En el downgrade, no revertimos los datos rellenados.
    pass
    # ### end Alembic commands ###
